[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2021"
license = "MPL-2.0"

[workspace.dependencies]
anyhow = "1.0.97"
daft = { version = "0.1.2", features = ["derive"] }
derive-where = "1.2.7"
hashbrown = "0.15.2"
proptest = "1.6.0"
rustc-hash = "2.1.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
test-strategy = "0.4.1"
