[package]
name = "id-map"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
daft = { version = "0.1.2", features = ["derive"] }
derive-where = "1.2.7"
hashbrown = "0.15.2"
serde = { version = "1.0.219", features = ["derive"], optional = true }

[dev-dependencies]
anyhow = "1.0.97"
proptest = "1.6.0"
serde_json = "1.0.140"
test-strategy = "0.4.1"

[features]
serde = ["dep:serde"]
