[package]
name = "iddqd"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
daft.workspace = true
derive-where.workspace = true
hashbrown.workspace = true
rustc-hash.workspace = true
serde = { workspace = true, optional = true }

[dev-dependencies]
anyhow.workspace = true
proptest.workspace = true
serde_json.workspace = true
test-strategy.workspace = true

[features]
serde = ["dep:serde"]
